// <auto-generated />
using System;
using AppointmentBillingService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppointmentBillingService.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    [Migration("20220405173327_Initial1")]
    partial class Initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppointmentBillingService.Models.AmbulanceService", b =>
                {
                    b.Property<int>("AmbulanceServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AmbulanceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Charge")
                        .HasColumnType("int");

                    b.HasKey("AmbulanceServiceId");

                    b.ToTable("AmbulanceServices");

                    b.HasData(
                        new
                        {
                            AmbulanceServiceId = 1,
                            AmbulanceType = "Air Ambulance",
                            Charge = 2000
                        },
                        new
                        {
                            AmbulanceServiceId = 2,
                            AmbulanceType = "Life Support Ambulance",
                            Charge = 1000
                        },
                        new
                        {
                            AmbulanceServiceId = 3,
                            AmbulanceType = "Isolation Ambulance",
                            Charge = 3000
                        });
                });

            modelBuilder.Entity("AppointmentBillingService.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfAppointment")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.ToTable("DoctorAppointments");
                });

            modelBuilder.Entity("AppointmentBillingService.Models.Billing", b =>
                {
                    b.Property<int>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmbulanceServiceCharge")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultationsCharge")
                        .HasColumnType("int");

                    b.Property<int>("ECGServiceCharge")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int>("LaboratoryServiceCharge")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhysiotherapyServiceCharge")
                        .HasColumnType("int");

                    b.Property<int>("RadiologyServiceCharge")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("BillingId");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("AppointmentBillingService.Models.Consultation", b =>
                {
                    b.Property<int>("ConsultationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Charge")
                        .HasColumnType("int");

                    b.Property<string>("ConsultationType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsultationId");

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            ConsultationId = 1,
                            Charge = 500,
                            ConsultationType = "Dermatology"
                        },
                        new
                        {
                            ConsultationId = 2,
                            Charge = 400,
                            ConsultationType = "General Medicine"
                        },
                        new
                        {
                            ConsultationId = 3,
                            Charge = 450,
                            ConsultationType = "Gynaecology"
                        },
                        new
                        {
                            ConsultationId = 4,
                            Charge = 600,
                            ConsultationType = "Neurology"
                        },
                        new
                        {
                            ConsultationId = 5,
                            Charge = 300,
                            ConsultationType = "Dentistry"
                        });
                });

            modelBuilder.Entity("AppointmentBillingService.Models.ECGService", b =>
                {
                    b.Property<int>("ECGServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Charge")
                        .HasColumnType("int");

                    b.Property<string>("ECGServiceType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ECGServiceId");

                    b.ToTable("ECGServices");

                    b.HasData(
                        new
                        {
                            ECGServiceId = 1,
                            Charge = 2000,
                            ECGServiceType = "Heart Fuctionality Test"
                        },
                        new
                        {
                            ECGServiceId = 2,
                            Charge = 3000,
                            ECGServiceType = "ECHO Cardiogram Test"
                        },
                        new
                        {
                            ECGServiceId = 3,
                            Charge = 1000,
                            ECGServiceType = "Trademill Test"
                        });
                });

            modelBuilder.Entity("AppointmentBillingService.Models.FacilityAppointment", b =>
                {
                    b.Property<int>("FacilityAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AmbulanceServiceId")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<int?>("ECGServiceId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int?>("LaboratoryServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("PhysiotherapyServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("RadiologyServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilityAppointmentId");

                    b.ToTable("FacilityAppointments");
                });

            modelBuilder.Entity("AppointmentBillingService.Models.LaboratoryService", b =>
                {
                    b.Property<int>("LaboratoryServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Charge")
                        .HasColumnType("int");

                    b.Property<string>("LaboratoryType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LaboratoryServiceId");

                    b.ToTable("LaboratoryServices");

                    b.HasData(
                        new
                        {
                            LaboratoryServiceId = 1,
                            Charge = 700,
                            LaboratoryType = "Liver Function Test"
                        },
                        new
                        {
                            LaboratoryServiceId = 2,
                            Charge = 400,
                            LaboratoryType = "Throid Function Test"
                        },
                        new
                        {
                            LaboratoryServiceId = 3,
                            Charge = 600,
                            LaboratoryType = "Renal Function Test"
                        },
                        new
                        {
                            LaboratoryServiceId = 4,
                            Charge = 900,
                            LaboratoryType = "Blood Sugar Test"
                        },
                        new
                        {
                            LaboratoryServiceId = 5,
                            Charge = 300,
                            LaboratoryType = "Gastric Function Test"
                        });
                });

            modelBuilder.Entity("AppointmentBillingService.Models.PhysiotherapyService", b =>
                {
                    b.Property<int>("PhysiotherapyServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Charge")
                        .HasColumnType("int");

                    b.Property<string>("PhysiotherapyType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhysiotherapyServiceId");

                    b.ToTable("PhysiotherapyServices");

                    b.HasData(
                        new
                        {
                            PhysiotherapyServiceId = 1,
                            Charge = 1000,
                            PhysiotherapyType = "Sports Physiotherapy"
                        },
                        new
                        {
                            PhysiotherapyServiceId = 2,
                            Charge = 2000,
                            PhysiotherapyType = "Pain Management"
                        },
                        new
                        {
                            PhysiotherapyServiceId = 3,
                            Charge = 3000,
                            PhysiotherapyType = "Neurological physiotherapy"
                        });
                });

            modelBuilder.Entity("AppointmentBillingService.Models.RadiologyService", b =>
                {
                    b.Property<int>("RadiologyServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Charge")
                        .HasColumnType("int");

                    b.Property<string>("RadiologyType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RadiologyServiceId");

                    b.ToTable("RadiologyService");

                    b.HasData(
                        new
                        {
                            RadiologyServiceId = 1,
                            Charge = 500,
                            RadiologyType = "Xray"
                        },
                        new
                        {
                            RadiologyServiceId = 2,
                            Charge = 400,
                            RadiologyType = "CT Scan"
                        },
                        new
                        {
                            RadiologyServiceId = 3,
                            Charge = 600,
                            RadiologyType = "Ultrasound"
                        },
                        new
                        {
                            RadiologyServiceId = 4,
                            Charge = 700,
                            RadiologyType = "MRI"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
